### ISSUE TITLE
Game crashes almost every time

### ISSUE THREAD

**Issue by Yyote** [Star-Wars-A-Cosmos-Divided-DevTeam/Star-Wars-A-Cosmos-Divided#88]
04/21/2024 08:48:31  |  Logging successful initialized.
04/21/2024 08:48:31  |  .NET Runtime Version: 7.0.16
04/21/2024 08:48:31  |  Running as a 64-bit process.
04/21/2024 08:48:31  |  Locale: ru-RU
04/21/2024 08:48:31  |  Language: ru-RU
04/21/2024 08:48:31  |  Executable path: C:\Program Files (x86)\Steam\steamapps\common\Cosmoteer\Bin\Cosmoteer.exe
04/21/2024 08:48:31  |  Cosmoteer version 0.26.0 build 0.26.0_steam
04/21/2024 08:48:31  |  Build Date: 13.03.2024 23:42:28
04/21/2024 08:48:31  |  Build Commit: 8a2fbf2a64436b2fee538eddc3473ab083ce0e88
04/21/2024 08:48:31  |  Steam API successfully initialized.
04/21/2024 08:48:32  |  Майкрософт Windows 10 Pro 64-разрядная 10.0.19045
04/21/2024 08:48:32  |  AMD Ryzen 5 6600H with Radeon Graphics          (12 logical / 6 physical cores)
04/21/2024 08:48:32  |  15557,0 MB RAM
04/21/2024 08:48:32  |  NVIDIA GeForce RTX 3050 Laptop GPU (31.0.15.4665) (12.01.2024)
04/21/2024 08:48:32  |  4095,0 MB VRAM
04/21/2024 08:48:32  |  
04/21/2024 08:48:32  |  Loaded app settings.
04/21/2024 08:48:32  |  Set application DPI mode: PerMonitor
04/21/2024 08:48:32  |  Setup default cursor.
04/21/2024 08:48:32  |  Using display adapter 0
04/21/2024 08:48:32  |  Created DXGI factory.
04/21/2024 08:48:32  |  Adapter #0: NVIDIA GeForce RTX 3050 Laptop GPU
04/21/2024 08:48:32  |  	Output #0: Generic PnP Monitor  (1920x1080)
04/21/2024 08:48:32  |  Adapter #1: AMD Radeon(TM) Graphics
04/21/2024 08:48:32  |  Adapter #2: Microsoft Basic Render Driver
04/21/2024 08:48:32  |  Updated Windows form configuration for borderless window.
04/21/2024 08:48:32  |  Created Windows form.
04/21/2024 08:48:32  |  Direct3D Feature Level: Level_11_0
04/21/2024 08:48:32  |  Created Direct3D 11 Device.
04/21/2024 08:48:32  |  Created swap chain: 1920x1080.
04/21/2024 08:48:32  |  Created window.
04/21/2024 08:48:32  |  Created clock.
04/21/2024 08:48:32  |  Created graphics manager.
04/21/2024 08:48:32  |  Max Texture Size: {X=16384 ,Y=16384}
04/21/2024 08:48:33  |  Created XAudio2 device.
04/21/2024 08:48:33  |  Created audio manager.
04/21/2024 08:48:33  |  Created input manager.
04/21/2024 08:48:33  |  Created default font.
04/21/2024 08:48:33  |  Initial app state is 'MainMenu'
04/21/2024 08:48:33  |  Initial application settings:
04/21/2024 08:48:33  |  	LastGameVersion: 
04/21/2024 08:48:33  |  	IsFirstBoot: True
04/21/2024 08:48:33  |  	InitState: MainMenu
04/21/2024 08:48:33  |  	Language: 
04/21/2024 08:48:33  |  	LockCursor: False
04/21/2024 08:48:33  |  	EdgePanMode: Analog
04/21/2024 08:48:33  |  	EdgePanSpeed: 15
04/21/2024 08:48:33  |  	KeyboardPanSpeed: 15
04/21/2024 08:48:33  |  	KeyboardZoomSpeed: 10
04/21/2024 08:48:33  |  	KeyboardRotSpeed: 90°
04/21/2024 08:48:33  |  	EnableMouseWheelZoom: True
04/21/2024 08:48:33  |  	InvertMouseWheelZoom: False
04/21/2024 08:48:33  |  	MouseWheelZoomSpeed: 1,12
04/21/2024 08:48:33  |  	MouseWheelZoomAtCursor: True
04/21/2024 08:48:33  |  	AutoTrackOnScreenShips: True
04/21/2024 08:48:33  |  	StickyFocus: True
04/21/2024 08:48:33  |  	DpiScaleMode: Dpi125
04/21/2024 08:48:33  |  	AnimateBackgrounds: True
04/21/2024 08:48:33  |  	BackgroundGridStyle: Crosses
04/21/2024 08:48:33  |  	FancyLighting: True
04/21/2024 08:48:33  |  	FancyParticles: True
04/21/2024 08:48:33  |  	FancyUIEffects: True
04/21/2024 08:48:33  |  	UncompressedTextures: False
04/21/2024 08:48:33  |  	ResolutionScale: 1,25
04/21/2024 08:48:33  |  	PlanetResolutionScale: 1
04/21/2024 08:48:33  |  	TargetFps: FpsTarget30
04/21/2024 08:48:33  |  	PostShaderIndex: 0
04/21/2024 08:48:33  |  	AllowShipDeselection: False
04/21/2024 08:48:33  |  	CtrlSelectsParts: True
04/21/2024 08:48:33  |  	EnableCollisionAvoidance: True
04/21/2024 08:48:33  |  	EnableArrivalMatching: True
04/21/2024 08:48:33  |  	AutoRecallCrew: True
04/21/2024 08:48:33  |  	PreferBlueprintMode: False
04/21/2024 08:48:33  |  	BlueprintAutoPause: True
04/21/2024 08:48:33  |  	ShowInvalidBlueprints: True
04/21/2024 08:48:33  |  	ShowMissingPartsWarning: True
04/21/2024 08:48:33  |  	ShowAutoRemovedParts: True
04/21/2024 08:48:33  |  	ShowAutoRemovedDecals: True
04/21/2024 08:48:33  |  	BuildAutoRotate: True
04/21/2024 08:48:33  |  	BuildAutoInteriors: True
04/21/2024 08:48:33  |  	PaintAutoRotate: True
04/21/2024 08:48:33  |  	PaintAllowOverwrite: True
04/21/2024 08:48:33  |  	BuildAllowOverwrite: True
04/21/2024 08:48:33  |  	BuildAutoDoors: True
04/21/2024 08:48:33  |  	RequirePartialRefundConfirmation: True
04/21/2024 08:48:33  |  	BuildShowNearestPaths: True
04/21/2024 08:48:33  |  	BuildAllowInsufficientCommand: False
04/21/2024 08:48:33  |  	ShowStatBars: True
04/21/2024 08:48:33  |  	ConstructExitsBuild: False
04/21/2024 08:48:33  |  	CrewAutoRotate: True
04/21/2024 08:48:33  |  	ShowCrewPaths: True
04/21/2024 08:48:33  |  	ShowCrewHomes: True
04/21/2024 08:48:33  |  	ShowUnselectedCrewAssignment: True
04/21/2024 08:48:33  |  	DefaultRoles: 
04/21/2024 08:48:33  |  	ResourcesAutoRotate: True
04/21/2024 08:48:33  |  	ShowResourceCounts: True
04/21/2024 08:48:33  |  	ShowResourceTransfers: True
04/21/2024 08:48:33  |  	ShowConstructionResourceDeliveries: True
04/21/2024 08:48:33  |  	ShowAllResourceTypes: False
04/21/2024 08:48:33  |  	ShowUnselectedResourceAssignment: True
04/21/2024 08:48:33  |  	RowsOfParts: 1
04/21/2024 08:48:33  |  	GrabLeavesCorridors: True
04/21/2024 08:48:33  |  	RepairAutoDoors: True
04/21/2024 08:48:33  |  	DiscardBlueprintsWhenCanceling: True
04/21/2024 08:48:33  |  	PartToolTips: True
04/21/2024 08:48:33  |  	PartToolTipsDefaultToStats: False
04/21/2024 08:48:33  |  	AutoSave: True
04/21/2024 08:48:33  |  	AutoSavesToKeep: 25
04/21/2024 08:48:33  |  	QuickSavesToKeep: 25
04/21/2024 08:48:33  |  	AutoSaveInterval: 600
04/21/2024 08:48:33  |  	SaveLostShips: True
04/21/2024 08:48:33  |  	LostShipsToKeep: 25
04/21/2024 08:48:33  |  	FtlAutoSave: True
04/21/2024 08:48:33  |  	ResourceDisplayMode: Context
04/21/2024 08:48:33  |  	ShowOnShipIndicators: True
04/21/2024 08:48:33  |  	ShowZoomedOutBlips: True
04/21/2024 08:48:33  |  	ShowOffScreenBlips: True
04/21/2024 08:48:33  |  	ShowBreadcrumbTrails: True
04/21/2024 08:48:33  |  	AutoPauseOnLostFocus: True
04/21/2024 08:48:33  |  	AutoSlowWhenEnemySpotted: 1
04/21/2024 08:48:33  |  	ScreenShake: True
04/21/2024 08:48:33  |  	UIAnimations: True
04/21/2024 08:48:33  |  	ShowMidpointFocusWidget: True
04/21/2024 08:48:33  |  	DefaultScreenshotFormat: Jpeg
04/21/2024 08:48:33  |  	PreferBorderlessWindowToggle: False
04/21/2024 08:48:33  |  	MasterVolume: 0,5
04/21/2024 08:48:33  |  	EffectsVolume: 1
04/21/2024 08:48:33  |  	MusicVolume: 1
04/21/2024 08:48:33  |  	InterfaceVolume: 1
04/21/2024 08:48:33  |  	MuteWhenUnfocused: False
04/21/2024 08:48:33  |  	PlayFriendlyPings: True
04/21/2024 08:48:33  |  	PlayEnemyPings: True
04/21/2024 08:48:33  |  	ShowTutorials: True
04/21/2024 08:48:33  |  	AutoCollectNuggets: True
04/21/2024 08:48:33  |  	DefaultPaintScheme: 
04/21/2024 08:48:33  |  	PaintSchemes: System.Collections.Generic.List`1[Cosmoteer.Ships.Paint.PaintScheme]
04/21/2024 08:48:33  |  	DefaultBuildTool: Grab
04/21/2024 08:48:33  |  	DefaultDecalTool: Grab
04/21/2024 08:48:33  |  	CodexPageStates: System.Collections.Generic.Dictionary`2[System.String,Cosmoteer.Codex.CodexPageState]
04/21/2024 08:48:33  |  	DontDimDialogBackgrounds: False
04/21/2024 08:48:33  |  	DontFlickerBlueprints: False
04/21/2024 08:48:33  |  	PlayerColor: 
04/21/2024 08:48:33  |  	EnemyColor: 
04/21/2024 08:48:33  |  	AllyColor: 
04/21/2024 08:48:33  |  	NeutralColor: 
04/21/2024 08:48:33  |  	RotateMinimap: True
04/21/2024 08:48:33  |  	MiniviewInCombatMode: Auto
04/21/2024 08:48:33  |  	MiniviewNotInCombatMode: Auto
04/21/2024 08:48:33  |  	MiniviewLockRotation: False
04/21/2024 08:48:33  |  	MiniviewSize: 
04/21/2024 08:48:33  |  	ShowInteriors: False
04/21/2024 08:48:33  |  	ShowAllCommands: False
04/21/2024 08:48:33  |  	AlwaysShowCommandWidgets: False
04/21/2024 08:48:33  |  	ShowSelectedPartStatusBars: True
04/21/2024 08:48:33  |  	ShowSpaceCrewLines: True
04/21/2024 08:48:33  |  	ShowResourcePickupLines: True
04/21/2024 08:48:33  |  	PreferWorldRelativeAttackAngle: False
04/21/2024 08:48:33  |  	PreferWorldRelativeFollowAngle: False
04/21/2024 08:48:33  |  	DirectControlEnableWeapons: True
04/21/2024 08:48:33  |  	DirectControlAimAssist: True
04/21/2024 08:48:33  |  	DirectControlAutoBrake: True
04/21/2024 08:48:33  |  	DirectControlAutoFaceCursor: False
04/21/2024 08:48:33  |  	DirectControlViewFollowsCursor: False
04/21/2024 08:48:33  |  	DirectControlAutoRotateView: False
04/21/2024 08:48:33  |  	DirectControlLockCameraToShip: False
04/21/2024 08:48:33  |  	DirectControlAutoZoomView: False
04/21/2024 08:48:33  |  	DirectControlShowWeaponCoverage: False
04/21/2024 08:48:33  |  	ShipLibraryLargeIcons: False
04/21/2024 08:48:33  |  	BreakFormationToAttack: True
04/21/2024 08:48:33  |  	DisplayAllShips: False
04/21/2024 08:48:33  |  	ShowAdvancedCommands: False
04/21/2024 08:48:33  |  	EnabledMods: System.Collections.Generic.HashSet`1[Halfling.IO.AbsolutePath]
04/21/2024 08:48:33  |  	AutoDisableMods: True
04/21/2024 08:48:33  |  	DeleteFileOnStartup: 
04/21/2024 08:48:33  |  	DefaultCreativeModeMapSize: 0
04/21/2024 08:48:33  |  	DefaultCreativeModeSimGenFlags: None
04/21/2024 08:48:33  |  	DefaultCareerModeCombatDifficulty: -1
04/21/2024 08:48:33  |  	DefaultCareerModeEconDifficulty: -1
04/21/2024 08:48:33  |  	DefaultCareerModeMapSize: 0
04/21/2024 08:48:33  |  	DefaultCareerModeCrewScarcity: -1
04/21/2024 08:48:33  |  	DefaultCareerModeDisableCrewConstruction: False
04/21/2024 08:48:33  |  	DefaultCareerModeDisableExploration: False
04/21/2024 08:48:33  |  	DefaultCareerModeDisableSalvaging: False
04/21/2024 08:48:33  |  	DefaultCareerModeStarterShip: 0
04/21/2024 08:48:33  |  	MPBlipColorMode: FriendAndFoe
04/21/2024 08:48:33  |  	MPShowDamagePoints: True
04/21/2024 08:48:33  |  	EnableDesyncDebugging: False
04/21/2024 08:48:33  |  	MaxSendRate: 1000
04/21/2024 08:48:33  |  	CustomRulesets: System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.List`1[Cosmoteer.CustomRuleset]]
04/21/2024 08:48:33  |  	PreferLAN: False
04/21/2024 08:48:33  |  	PreferredLobbyType: CoOp
04/21/2024 08:48:33  |  	ShowNewsOnStartup: True
04/21/2024 08:48:33  |  	ShowTipsOnStartup: True
04/21/2024 08:48:33  |  	ReadNewsArticles: System.Collections.Generic.HashSet`1[System.String]
04/21/2024 08:48:33  |  	ShowNewsAlerts: True
04/21/2024 08:48:33  |  	HiddenNewsAlerts: System.Collections.Generic.HashSet`1[System.String]
04/21/2024 08:48:33  |  	MainMenuBackgroundIndex: 0
04/21/2024 08:48:33  |  	CycleMainMenuBackground: True
04/21/2024 08:48:33  |  	DefaultAuthorName: 
04/21/2024 08:48:33  |  	EnableGifRecorder: False
04/21/2024 08:48:33  |  	GifRecorderSeconds: 10
04/21/2024 08:48:33  |  	GifRecorderFramerate: 20
04/21/2024 08:48:33  |  	GifRecorderResolution: 480
04/21/2024 08:48:33  |  	ShowNearbyMissionsCount: 3
04/21/2024 08:48:33  |  	DevModeSPRecording: False
04/21/2024 08:48:33  |  	DevModeSPRecordingAutoLoad: False
04/21/2024 08:48:33  |  	KeepLogFiles: 10
04/21/2024 08:48:33  |  	KeepRecFiles: 10
04/21/2024 08:48:33  |  	RestoreZoomOnToolboxExit: True
04/21/2024 08:48:33  |  	ZoomOutOnFtl: True
04/21/2024 08:48:33  |  	LoadBlueprintPaint: False
04/21/2024 08:48:33  |  	LoadBlueprintRoles: False
04/21/2024 08:48:33  |  	LoadBlueprintReplaceInsteadOfAdd: False
04/21/2024 08:48:33  |  	LoadBlueprintCrew: False
04/21/2024 08:48:33  |  	LoadBlueprintResources: False
04/21/2024 08:48:33  |  	LoadBlueprintsFlightInfo: False
04/21/2024 08:48:33  |  	LoadBlueprintTextInfo: False
04/21/2024 08:48:33  |  Multicore helper thread count: 5
04/21/2024 08:48:33  |  Starting main game loop...
04/21/2024 08:48:33  |  Enabled mods:
04/21/2024 08:48:33  |  	[Workshop ID 3119336292] - 00.00.SW (1.0.RC)
04/21/2024 08:48:33  |  	[Workshop ID 3119349707] - SW.1.StarWars (1.0.rc3)
04/21/2024 08:48:33  |  	[Workshop ID 3029566606] - SW.4.StarWarsMusic (1.0.2)
04/21/2024 08:48:33  |  	[Built-in] - cosmoteer.huge_crews (1.0.0)
04/21/2024 08:48:33  |  	[Built-in] - cosmoteer.huge_ships (1.0.0)
04/21/2024 08:48:33  |  Loaded language 'ru'.
04/21/2024 08:48:49  |  Loaded game data in 16,4 seconds.
04/21/2024 08:49:28  |  Loaded game named 'Auto-Save 2024-04-21_08-45-23'.
04/21/2024 08:49:28  |  Game pushed onto stack.
04/21/2024 08:49:28  |  Game mode is: CreativeGameModeManager
04/21/2024 08:51:04  |  Starting part: {SW.IonThruster01_3x3_switchable; Location={X=7 ,Y=24}; Rotation=0; FlipX=False}
04/21/2024 08:51:04  |  Starting rect: {X=8, Y=25, Width=1, Height=1}
04/21/2024 08:51:04  |  Ending part: {SW.reactor_tiny; Location={X=4 ,Y=16}; Rotation=0; FlipX=False}
04/21/2024 08:51:04  |  Ending rect: {X=4, Y=16, Width=1, Height=1}
04/21/2024 08:51:04  |  Memory usage at time of crash: 4 226 867 200
04/21/2024 08:51:04  |  Application state stack at time of crash:
04/21/2024 08:51:04  |  	Cosmoteer.Game.GameRoot
04/21/2024 08:51:04  |  	Cosmoteer.Gui.TitleScreen
04/21/2024 08:51:04  |  FPS at time of crash: 24,215103
04/21/2024 08:51:04  |  Running processes at time of crash: amdfendrsr, atieclxx, atiesrxx, audiodg, browser, cmd, CompPkgSrv, conhost, Cosmoteer, csrss, ctfmon, dasHost, DiscSoftBusServiceUltra, dllhost, DTAgent, dwm, explorer, FMService64, FnHotkeyCapsLKNumLK, FnHotkeyUtility, fontdrvhost, GameOverlayUI, Idle, jucheck, jusched, LenovoUtilityService, LsaIso, lsass, LSB, NahimicService, NhNotifSys, nvcontainer, NVDisplay.Container, NVIDIA Web Helper, OfficeClickToRun, PenTablet, Registry, RtkAudUService64, RtkBtManServ, rundll32, RuntimeBroker, SearchApp, Secure System, service_update, services, sihost, smss, spoolsv, StartMenuExperienceHost, steam, steamwebhelper, svchost, System, taskhostw, TextInputHost, unsecapp, wininit, winlogon, WmiPrvSE, wslservice, WUDFHost, 
04/21/2024 08:51:04  |  System.AggregateException: A FastParallel task threw one or more exceptions. (A FastParallel task threw one or more exceptions. (Pathfind operation failed!))
04/21/2024 08:51:04  |   ---> System.AggregateException: A FastParallel task threw one or more exceptions. (Pathfind operation failed!)
04/21/2024 08:51:04  |   ---> System.InvalidOperationException: Pathfind operation failed!
04/21/2024 08:51:04  |     at Cosmoteer.Ships.Crew.Pathing.PathManager.FindPath(IntRect start, IntRect end, Boolean useTraffic) in C:\Users\walt\Documents\Code\Cosmoteer\Source\Ships\Crew\Pathing\PathManager.cs:line 202
04/21/2024 08:51:04  |     at Cosmoteer.Ships.Crew.Pathing.PathManager.FindPath(IntVector2 start, Destination end, Boolean useTraffic) in C:\Users\walt\Documents\Code\Cosmoteer\Source\Ships\Crew\Pathing\PathManager.cs:line 114
04/21/2024 08:51:04  |     at Cosmoteer.Ships.Crew.ShipCrew.Cosmoteer.Ships.Crew.ShipCrewManager.IShipCrewMembers.UpdateDestinationAsync() in C:\Users\walt\Documents\Code\Cosmoteer\Source\Ships\Crew\ShipCrew.cs:line 667
04/21/2024 08:51:04  |     at Cosmoteer.Ships.Crew.ShipCrewManager.UpdateCrewAsync(Int32 startIndex, Int32 endIndex) in C:\Users\walt\Documents\Code\Cosmoteer\Source\Ships\Crew\ShipCrewManager.cs:line 847
04/21/2024 08:51:04  |     at Halfling.Performance.FastParallel.RunParallelBatch(ParallelTask task, Int32 batch, List`1 profilerJobs) in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Performance\FastParallel.cs:line 370
04/21/2024 08:51:04  |     --- End of inner exception stack trace ---
04/21/2024 08:51:04  |     at Halfling.Performance.FastParallel.For(Int32 fromInclusive, Int32 toExclusive, FastParallelAction body, Object data, Boolean copyStackData, String profilerName) in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Performance\FastParallel.cs:line 239
04/21/2024 08:51:04  |     at Cosmoteer.Ships.Crew.ShipCrewManager.FixedUpdate(FixedUpdater fixedUpdater, SceneRoot root) in C:\Users\walt\Documents\Code\Cosmoteer\Source\Ships\Crew\ShipCrewManager.cs:line 775
04/21/2024 08:51:04  |     at Halfling.Scene2D.SceneComponent.Halfling.Scene2D.IFixedUpdateableSceneObject.FixedUpdate(FixedUpdater fixedUpdater, SceneRoot root) in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Scene2D\SceneComponent.cs:line 892
04/21/2024 08:51:04  |     at Cosmoteer.Simulation.SimRoot.<>c.<ParallelFixedUpdate>b__204_0(Int32 from, Int32 to, Object data) in C:\Users\walt\Documents\Code\Cosmoteer\Source\Simulation\SimRoot.cs:line 1345
04/21/2024 08:51:04  |     at Halfling.Performance.FastParallel.RunParallelBatch(ParallelTask task, Int32 batch, List`1 profilerJobs) in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Performance\FastParallel.cs:line 370
04/21/2024 08:51:04  |     --- End of inner exception stack trace ---
04/21/2024 08:51:04  |     at Halfling.Performance.FastParallel.For(Int32 fromInclusive, Int32 toExclusive, FastParallelAction body, Object data, Boolean copyStackData, String profilerName) in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Performance\FastParallel.cs:line 239
04/21/2024 08:51:04  |     at Cosmoteer.Simulation.SimRoot.ParallelFixedUpdate(Int32 bucket, IFixedUpdateableSceneObject[] array, Int32 startIndex, Int32 count) in C:\Users\walt\Documents\Code\Cosmoteer\Source\Simulation\SimRoot.cs:line 1336
04/21/2024 08:51:04  |     at Halfling.Scene2D.SceneRoot.FixedUpdateForBucket(Int32 bucket) in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Scene2D\SceneRoot.cs:line 1074
04/21/2024 08:51:04  |     at Cosmoteer.Simulation.SimRoot.FixedUpdateForBucket(Int32 bucket) in C:\Users\walt\Documents\Code\Cosmoteer\Source\Simulation\SimRoot.cs:line 1212
04/21/2024 08:51:04  |     at Halfling.Scene2D.SceneRoot.FixedUpdate() in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Scene2D\SceneRoot.cs:line 1067
04/21/2024 08:51:04  |     at Cosmoteer.Simulation.SimRoot.FixedUpdate() in C:\Users\walt\Documents\Code\Cosmoteer\Source\Simulation\SimRoot.cs:line 1200
04/21/2024 08:51:04  |     at Halfling.Timing.FixedUpdater.Advance(Action action) in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Timing\FixedUpdater.cs:line 109
04/21/2024 08:51:04  |     at Halfling.Scene2D.SceneRoot.DoFixedUpdates() in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Scene2D\SceneRoot.cs:line 1003
04/21/2024 08:51:04  |     at Halfling.Scene2D.SceneRoot.Update() in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Scene2D\SceneRoot.cs:line 746
04/21/2024 08:51:04  |     at Cosmoteer.Simulation.SimRoot.Update() in C:\Users\walt\Documents\Code\Cosmoteer\Source\Simulation\SimRoot.cs:line 654
04/21/2024 08:51:04  |     at Cosmoteer.Game.GameRoot.Update(Action updateParent) in C:\Users\walt\Documents\Code\Cosmoteer\Source\Game\GameRoot.cs:line 1882
04/21/2024 08:51:04  |     at Halfling.Application.AppStateEx.Halfling.Application.IAppState.Update(Action updateParent) in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Application\AppStateEx.cs:line 213
04/21/2024 08:51:04  |     at Halfling.Application.Director.CallUpdate() in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Application\Director.cs:line 1010
04/21/2024 08:51:04  |     at Halfling.Application.Director.DoUpdate() in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Application\Director.cs:line 934
04/21/2024 08:51:04  |     at Halfling.Application.Director.GetRunIterator()+MoveNext()
04/21/2024 08:51:04  |     at Halfling.Application.Bases.GenericApp.ApplicationMainIterator()+MoveNext() in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Application\Bases\GenericApp.cs:line 731
04/21/2024 08:51:04  |     at Halfling.Windows.D3D11.D3D11Window.<>c__DisplayClass105_0.<RunGameLoop>g___DoFrame|0() in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingPlatformWDX\Source\Windows\D3D11\D3D11Window.cs:line 947
04/21/2024 08:51:04  |     at Halfling.Windows.D3D11.D3D11Window.RunGameLoop(String[] args, IEnumerable`1 iterator) in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingPlatformWDX\Source\Windows\D3D11\D3D11Window.cs:line 814
04/21/2024 08:51:04  |     at Halfling.Application.Bases.GenericApp.ApplicationMain(String[] args) in C:\Users\walt\Documents\Code\Cosmoteer\Halfling\HalflingCore\Source\Application\Bases\GenericApp.cs:line 230
04/21/2024 08:51:04  |     at Cosmoteer.GameApp.Main(String[] args) in C:\Users\walt\Documents\Code\Cosmoteer\Source\GameApp.cs:line 156
04/21/2024 08:51:04  |  Actual data hash: 2a1e2a941fe6d01d16bbf13c49dff1a1
04/21/2024 08:51:04  |  Expected data hash: 2a1e2a941fe6d01d16bbf13c49dff1a1
04/21/2024 08:51:04  |  Director received exit call.
04/21/2024 08:51:04  |  Disposed default font.
04/21/2024 08:51:04  |  Disposed XA2AudioManager device.
04/21/2024 08:51:04  |  Disposed audio manager.
04/21/2024 08:51:04  |  Disposed clock.
04/21/2024 08:51:04  |  Disposed input manager.
04/21/2024 08:51:04  |  Disposed graphics manager.
04/21/2024 08:51:04  |  Disposed swap chain.
04/21/2024 08:51:04  |  Disposed Direct3D device.
04/21/2024 08:51:04  |  Disposed DXGI factory.
04/21/2024 08:51:04  |  Closed Windows form.
04/21/2024 08:51:04  |  Director received exit call.
04/21/2024 08:51:04  |  Disposed window.
04/21/2024 08:51:04  |  Disposed platform interface.
04/21/2024 08:51:04  |  Closing log output file...

**Comment by Rojamahorse** [comment]
Assuming you are using the latest dev builds (and not the steam version) this is fixed in our latest updates.  I believe this was a pathing error with the 7x10 Thrusters.
